# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rjsmi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz\forms\cluz_form_setup.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_setupDialog(object):
    def setupUi(self, setupDialog):
        setupDialog.setObjectName("setupDialog")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(setupDialog.sizePolicy().hasHeightForWidth())
        setupDialog.setSizePolicy(sizePolicy)
        setupDialog.setMinimumSize(QtCore.QSize(850, 500))
        self.gridLayout_2 = QtWidgets.QGridLayout(setupDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.setupIconLabel = QtWidgets.QLabel(setupDialog)
        self.setupIconLabel.setText("")
        self.setupIconLabel.setPixmap(QtGui.QPixmap(":/logos/images/setup_logo_panel.png"))
        self.setupIconLabel.setObjectName("setupIconLabel")
        self.horizontalLayout_5.addWidget(self.setupIconLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(setupDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.analysisLabel = QtWidgets.QLabel(setupDialog)
        self.analysisLabel.setTextFormat(QtCore.Qt.RichText)
        self.analysisLabel.setObjectName("analysisLabel")
        self.horizontalLayout_3.addWidget(self.analysisLabel)
        self.marxanRadioButton = QtWidgets.QRadioButton(setupDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.marxanRadioButton.setFont(font)
        self.marxanRadioButton.setChecked(True)
        self.marxanRadioButton.setObjectName("marxanRadioButton")
        self.horizontalLayout_3.addWidget(self.marxanRadioButton)
        self.mzonesRadioButton = QtWidgets.QRadioButton(setupDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mzonesRadioButton.setFont(font)
        self.mzonesRadioButton.setObjectName("mzonesRadioButton")
        self.horizontalLayout_3.addWidget(self.mzonesRadioButton)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.marxanLabel = QtWidgets.QLabel(setupDialog)
        self.marxanLabel.setObjectName("marxanLabel")
        self.gridLayout.addWidget(self.marxanLabel, 0, 0, 1, 1)
        self.outputButton = QtWidgets.QPushButton(setupDialog)
        self.outputButton.setMinimumSize(QtCore.QSize(75, 25))
        self.outputButton.setAutoDefault(False)
        self.outputButton.setObjectName("outputButton")
        self.gridLayout.addWidget(self.outputButton, 2, 2, 1, 1)
        self.puLabel = QtWidgets.QLabel(setupDialog)
        self.puLabel.setMinimumSize(QtCore.QSize(110, 16))
        self.puLabel.setObjectName("puLabel")
        self.gridLayout.addWidget(self.puLabel, 3, 0, 1, 1)
        self.marxanLineEdit = QtWidgets.QLineEdit(setupDialog)
        self.marxanLineEdit.setObjectName("marxanLineEdit")
        self.gridLayout.addWidget(self.marxanLineEdit, 0, 1, 1, 1)
        self.outputLabel = QtWidgets.QLabel(setupDialog)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout.addWidget(self.outputLabel, 2, 0, 1, 1)
        self.targetLineEdit = QtWidgets.QLineEdit(setupDialog)
        self.targetLineEdit.setObjectName("targetLineEdit")
        self.gridLayout.addWidget(self.targetLineEdit, 4, 1, 1, 1)
        self.inputLineEdit = QtWidgets.QLineEdit(setupDialog)
        self.inputLineEdit.setObjectName("inputLineEdit")
        self.gridLayout.addWidget(self.inputLineEdit, 1, 1, 1, 1)
        self.puButton = QtWidgets.QPushButton(setupDialog)
        self.puButton.setMinimumSize(QtCore.QSize(75, 25))
        self.puButton.setAutoDefault(False)
        self.puButton.setObjectName("puButton")
        self.gridLayout.addWidget(self.puButton, 3, 2, 1, 1)
        self.inputButton = QtWidgets.QPushButton(setupDialog)
        self.inputButton.setMinimumSize(QtCore.QSize(75, 25))
        self.inputButton.setAutoDefault(False)
        self.inputButton.setObjectName("inputButton")
        self.gridLayout.addWidget(self.inputButton, 1, 2, 1, 1)
        self.puLineEdit = QtWidgets.QLineEdit(setupDialog)
        self.puLineEdit.setObjectName("puLineEdit")
        self.gridLayout.addWidget(self.puLineEdit, 3, 1, 1, 1)
        self.inputLabel = QtWidgets.QLabel(setupDialog)
        self.inputLabel.setObjectName("inputLabel")
        self.gridLayout.addWidget(self.inputLabel, 1, 0, 1, 1)
        self.targetButton = QtWidgets.QPushButton(setupDialog)
        self.targetButton.setMinimumSize(QtCore.QSize(75, 25))
        self.targetButton.setAutoDefault(False)
        self.targetButton.setObjectName("targetButton")
        self.gridLayout.addWidget(self.targetButton, 4, 2, 1, 1)
        self.marxanButton = QtWidgets.QPushButton(setupDialog)
        self.marxanButton.setMinimumSize(QtCore.QSize(75, 25))
        self.marxanButton.setAutoDefault(False)
        self.marxanButton.setObjectName("marxanButton")
        self.gridLayout.addWidget(self.marxanButton, 0, 2, 1, 1)
        self.outputLineEdit = QtWidgets.QLineEdit(setupDialog)
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.gridLayout.addWidget(self.outputLineEdit, 2, 1, 1, 1)
        self.targetLabel = QtWidgets.QLabel(setupDialog)
        self.targetLabel.setObjectName("targetLabel")
        self.gridLayout.addWidget(self.targetLabel, 4, 0, 1, 1)
        self.zonesLineEdit = QtWidgets.QLineEdit(setupDialog)
        self.zonesLineEdit.setObjectName("zonesLineEdit")
        self.gridLayout.addWidget(self.zonesLineEdit, 5, 1, 1, 1)
        self.zonesButton = QtWidgets.QPushButton(setupDialog)
        self.zonesButton.setMinimumSize(QtCore.QSize(75, 25))
        self.zonesButton.setAutoDefault(False)
        self.zonesButton.setObjectName("zonesButton")
        self.gridLayout.addWidget(self.zonesButton, 5, 2, 1, 1)
        self.zonesLabel = QtWidgets.QLabel(setupDialog)
        self.zonesLabel.setEnabled(True)
        self.zonesLabel.setObjectName("zonesLabel")
        self.gridLayout.addWidget(self.zonesLabel, 5, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.precLabel = QtWidgets.QLabel(setupDialog)
        self.precLabel.setMinimumSize(QtCore.QSize(500, 24))
        self.precLabel.setObjectName("precLabel")
        self.horizontalLayout_2.addWidget(self.precLabel)
        self.precComboBox = QtWidgets.QComboBox(setupDialog)
        self.precComboBox.setMinimumSize(QtCore.QSize(0, 24))
        self.precComboBox.setSizeIncrement(QtCore.QSize(0, 16))
        self.precComboBox.setObjectName("precComboBox")
        self.horizontalLayout_2.addWidget(self.precComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.setupPathLabel = QtWidgets.QLabel(setupDialog)
        self.setupPathLabel.setObjectName("setupPathLabel")
        self.verticalLayout_2.addWidget(self.setupPathLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem3)
        self.saveButton = QtWidgets.QPushButton(setupDialog)
        self.saveButton.setMinimumSize(QtCore.QSize(90, 25))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.loadButton = QtWidgets.QPushButton(setupDialog)
        self.loadButton.setMinimumSize(QtCore.QSize(90, 25))
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.saveAsButton = QtWidgets.QPushButton(setupDialog)
        self.saveAsButton.setMinimumSize(QtCore.QSize(90, 25))
        self.saveAsButton.setObjectName("saveAsButton")
        self.horizontalLayout.addWidget(self.saveAsButton)
        self.cancelButton = QtWidgets.QPushButton(setupDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(90, 25))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout.setStretch(5, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(setupDialog)
        self.cancelButton.clicked.connect(setupDialog.close)
        self.marxanRadioButton.toggled['bool'].connect(self.zonesLabel.setHidden)
        self.marxanRadioButton.toggled['bool'].connect(self.zonesLineEdit.setHidden)
        self.marxanRadioButton.toggled['bool'].connect(self.zonesButton.setHidden)
        QtCore.QMetaObject.connectSlotsByName(setupDialog)

    def retranslateUi(self, setupDialog):
        _translate = QtCore.QCoreApplication.translate
        setupDialog.setWindowTitle(_translate("setupDialog", "Setup file settings"))
        self.label_2.setText(_translate("setupDialog", "<html><head/><body><p><a href=\"http://eepurl.com/geIHtf\"><span style=\" font-size:10pt; font-style:italic; text-decoration: underline; color:#0000ff;\">Please sign up to the CLUZ email list</span></a><span style=\" font-size:10pt; font-style:italic;\">, </span><span style=\" font-size:10pt; font-weight:400; font-style:italic;\">so we can contact you when new versions are released. This will also make fundraising for future improvements easier, as we can provide summaries on who is using CLUZ.</span></p></body></html>"))
        self.analysisLabel.setText(_translate("setupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Analysis type:</span></p></body></html>"))
        self.marxanRadioButton.setText(_translate("setupDialog", "Marxan"))
        self.mzonesRadioButton.setText(_translate("setupDialog", "Marxan with Zones"))
        self.marxanLabel.setText(_translate("setupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Marxan location</span></p></body></html>"))
        self.outputButton.setText(_translate("setupDialog", "Browse..."))
        self.puLabel.setText(_translate("setupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Planning unit theme</span></p></body></html>"))
        self.marxanLineEdit.setText(_translate("setupDialog", "blank"))
        self.outputLabel.setText(_translate("setupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Output directory</span></p></body></html>"))
        self.targetLineEdit.setText(_translate("setupDialog", "blank"))
        self.inputLineEdit.setText(_translate("setupDialog", "blank"))
        self.puButton.setText(_translate("setupDialog", "Browse..."))
        self.inputButton.setText(_translate("setupDialog", "Browse..."))
        self.puLineEdit.setText(_translate("setupDialog", "blank"))
        self.inputLabel.setText(_translate("setupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Input directory</span></p></body></html>"))
        self.targetButton.setText(_translate("setupDialog", "Browse..."))
        self.marxanButton.setText(_translate("setupDialog", "Browse..."))
        self.outputLineEdit.setText(_translate("setupDialog", "blank"))
        self.targetLabel.setText(_translate("setupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Target table</span></p></body></html>"))
        self.zonesLineEdit.setText(_translate("setupDialog", "blank"))
        self.zonesButton.setText(_translate("setupDialog", "Browse..."))
        self.zonesLabel.setText(_translate("setupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Zones table</span></p></body></html>"))
        self.precLabel.setText(_translate("setupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Decimal places for numbers in Abundance and Target tables                    </span></p></body></html>"))
        self.setupPathLabel.setText(_translate("setupDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Setup file location</span>: blank</p></body></html>"))
        self.saveButton.setText(_translate("setupDialog", "Save"))
        self.loadButton.setText(_translate("setupDialog", "Load"))
        self.saveAsButton.setText(_translate("setupDialog", "Save As..."))
        self.cancelButton.setText(_translate("setupDialog", "Close"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    setupDialog = QtWidgets.QDialog()
    ui = Ui_setupDialog()
    ui.setupUi(setupDialog)
    setupDialog.show()
    sys.exit(app.exec_())

