# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rjsmi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz\forms\cluz_form_load.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_loadDialog(object):
    def setupUi(self, loadDialog):
        loadDialog.setObjectName("loadDialog")
        loadDialog.setMinimumSize(QtCore.QSize(700, 430))
        self.gridLayout = QtWidgets.QGridLayout(loadDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.logoLabel = QtWidgets.QLabel(loadDialog)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/logos/images/setup_logo_panel.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_7.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.bestCheckBox = QtWidgets.QCheckBox(loadDialog)
        self.bestCheckBox.setObjectName("bestCheckBox")
        self.verticalLayout.addWidget(self.bestCheckBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bestLineEdit = QtWidgets.QLineEdit(loadDialog)
        self.bestLineEdit.setMaxLength(32766)
        self.bestLineEdit.setObjectName("bestLineEdit")
        self.horizontalLayout_2.addWidget(self.bestLineEdit)
        self.bestButton = QtWidgets.QPushButton(loadDialog)
        self.bestButton.setObjectName("bestButton")
        self.horizontalLayout_2.addWidget(self.bestButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bestLabel = QtWidgets.QLabel(loadDialog)
        self.bestLabel.setObjectName("bestLabel")
        self.horizontalLayout_4.addWidget(self.bestLabel)
        self.bestNameLineEdit = QtWidgets.QLineEdit(loadDialog)
        self.bestNameLineEdit.setObjectName("bestNameLineEdit")
        self.horizontalLayout_4.addWidget(self.bestNameLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.summedCheckBox = QtWidgets.QCheckBox(loadDialog)
        self.summedCheckBox.setObjectName("summedCheckBox")
        self.verticalLayout.addWidget(self.summedCheckBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.summedLineEdit = QtWidgets.QLineEdit(loadDialog)
        self.summedLineEdit.setObjectName("summedLineEdit")
        self.horizontalLayout_3.addWidget(self.summedLineEdit)
        self.summedButton = QtWidgets.QPushButton(loadDialog)
        self.summedButton.setObjectName("summedButton")
        self.horizontalLayout_3.addWidget(self.summedButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.summedLabel = QtWidgets.QLabel(loadDialog)
        self.summedLabel.setObjectName("summedLabel")
        self.horizontalLayout_6.addWidget(self.summedLabel)
        self.summedNameLineEdit = QtWidgets.QLineEdit(loadDialog)
        self.summedNameLineEdit.setObjectName("summedNameLineEdit")
        self.horizontalLayout_6.addWidget(self.summedNameLineEdit)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem6)
        self.okButton = QtWidgets.QPushButton(loadDialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem7)
        self.cancelButton = QtWidgets.QPushButton(loadDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem8)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)

        self.retranslateUi(loadDialog)
        self.cancelButton.clicked.connect(loadDialog.close)
        self.bestCheckBox.clicked['bool'].connect(self.bestLabel.setVisible)
        self.bestCheckBox.clicked['bool'].connect(self.bestNameLineEdit.setVisible)
        self.summedCheckBox.clicked['bool'].connect(self.summedLabel.setVisible)
        self.summedCheckBox.clicked['bool'].connect(self.summedNameLineEdit.setVisible)
        self.bestCheckBox.clicked['bool'].connect(self.bestLineEdit.setVisible)
        self.bestCheckBox.clicked['bool'].connect(self.bestButton.setVisible)
        self.summedCheckBox.clicked['bool'].connect(self.summedLineEdit.setVisible)
        self.summedCheckBox.clicked['bool'].connect(self.summedButton.setVisible)
        QtCore.QMetaObject.connectSlotsByName(loadDialog)

    def retranslateUi(self, loadDialog):
        _translate = QtCore.QCoreApplication.translate
        loadDialog.setWindowTitle(_translate("loadDialog", "Load previous Marxan results"))
        self.bestCheckBox.setText(_translate("loadDialog", "Load best solution results (default name is *_best.txt)"))
        self.bestButton.setText(_translate("loadDialog", "Browse"))
        self.bestLabel.setText(_translate("loadDialog", "New best field name"))
        self.summedCheckBox.setText(_translate("loadDialog", "Load summed solution results (default name is *_ssoln.txt)"))
        self.summedButton.setText(_translate("loadDialog", "Browse"))
        self.summedLabel.setText(_translate("loadDialog", "New summed solution field name"))
        self.okButton.setText(_translate("loadDialog", "OK"))
        self.cancelButton.setText(_translate("loadDialog", "Cancel"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loadDialog = QtWidgets.QDialog()
    ui = Ui_loadDialog()
    ui.setupUi(loadDialog)
    loadDialog.show()
    sys.exit(app.exec_())

