# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rjsmi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz\forms\cluz_form_distribution.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_distributionDialog(object):
    def setupUi(self, distributionDialog):
        distributionDialog.setObjectName("distributionDialog")
        distributionDialog.setMinimumSize(QtCore.QSize(730, 500))
        self.gridLayout = QtWidgets.QGridLayout(distributionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logoLabel = QtWidgets.QLabel(distributionDialog)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/logos/images/setup_logo_panel.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_3.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.featLabel = QtWidgets.QLabel(distributionDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.featLabel.sizePolicy().hasHeightForWidth())
        self.featLabel.setSizePolicy(sizePolicy)
        self.featLabel.setMinimumSize(QtCore.QSize(421, 24))
        self.featLabel.setObjectName("featLabel")
        self.verticalLayout_2.addWidget(self.featLabel)
        self.featListWidget = QtWidgets.QListWidget(distributionDialog)
        self.featListWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.featListWidget.setObjectName("featListWidget")
        self.verticalLayout_2.addWidget(self.featListWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.catFeatLabel = QtWidgets.QLabel(distributionDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catFeatLabel.sizePolicy().hasHeightForWidth())
        self.catFeatLabel.setSizePolicy(sizePolicy)
        self.catFeatLabel.setMinimumSize(QtCore.QSize(421, 24))
        self.catFeatLabel.setObjectName("catFeatLabel")
        self.verticalLayout.addWidget(self.catFeatLabel)
        self.intervalRadioButton = QtWidgets.QRadioButton(distributionDialog)
        self.intervalRadioButton.setMinimumSize(QtCore.QSize(0, 24))
        self.intervalRadioButton.setChecked(True)
        self.intervalRadioButton.setObjectName("intervalRadioButton")
        self.verticalLayout.addWidget(self.intervalRadioButton)
        self.areaRadioButton = QtWidgets.QRadioButton(distributionDialog)
        self.areaRadioButton.setMinimumSize(QtCore.QSize(0, 24))
        self.areaRadioButton.setObjectName("areaRadioButton")
        self.verticalLayout.addWidget(self.areaRadioButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.filePathlabel = QtWidgets.QLabel(distributionDialog)
        self.filePathlabel.setMinimumSize(QtCore.QSize(351, 16))
        self.filePathlabel.setObjectName("filePathlabel")
        self.verticalLayout_2.addWidget(self.filePathlabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filePathlineEdit = QtWidgets.QLineEdit(distributionDialog)
        self.filePathlineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.filePathlineEdit.setObjectName("filePathlineEdit")
        self.horizontalLayout_2.addWidget(self.filePathlineEdit)
        self.filePathButton = QtWidgets.QPushButton(distributionDialog)
        self.filePathButton.setMinimumSize(QtCore.QSize(0, 26))
        self.filePathButton.setObjectName("filePathButton")
        self.horizontalLayout_2.addWidget(self.filePathButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem3)
        self.okButton = QtWidgets.QPushButton(distributionDialog)
        self.okButton.setMinimumSize(QtCore.QSize(0, 24))
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem4)
        self.cancelButton = QtWidgets.QPushButton(distributionDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(0, 24))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem5)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(distributionDialog)
        self.cancelButton.clicked.connect(distributionDialog.close)
        QtCore.QMetaObject.connectSlotsByName(distributionDialog)

    def retranslateUi(self, distributionDialog):
        _translate = QtCore.QCoreApplication.translate
        distributionDialog.setWindowTitle(_translate("distributionDialog", "Show distribution of features"))
        self.featLabel.setText(_translate("distributionDialog", "Select conservation features to display"))
        self.catFeatLabel.setText(_translate("distributionDialog", "Choose legend categories"))
        self.intervalRadioButton.setText(_translate("distributionDialog", "Equal  interval"))
        self.areaRadioButton.setText(_translate("distributionDialog", "Equal area"))
        self.filePathlabel.setText(_translate("distributionDialog", "Name of shapefile that will be produced:"))
        self.filePathButton.setText(_translate("distributionDialog", "Browse"))
        self.okButton.setText(_translate("distributionDialog", "OK"))
        self.cancelButton.setText(_translate("distributionDialog", "Cancel"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    distributionDialog = QtWidgets.QDialog()
    ui = Ui_distributionDialog()
    ui.setupUi(distributionDialog)
    distributionDialog.show()
    sys.exit(app.exec_())

