# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rjsmi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz\forms\cluz_form_zones_transform.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_zonesTransformDialog(object):
    def setupUi(self, zonesTransformDialog):
        zonesTransformDialog.setObjectName("zonesTransformDialog")
        zonesTransformDialog.setMinimumSize(QtCore.QSize(760, 400))
        self.gridLayout_3 = QtWidgets.QGridLayout(zonesTransformDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logoLabel = QtWidgets.QLabel(zonesTransformDialog)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/logos/images/setup_logo_panel.png"))
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_3.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.setupPathLabel = QtWidgets.QLabel(zonesTransformDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setupPathLabel.sizePolicy().hasHeightForWidth())
        self.setupPathLabel.setSizePolicy(sizePolicy)
        self.setupPathLabel.setObjectName("setupPathLabel")
        self.verticalLayout.addWidget(self.setupPathLabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.folderButton = QtWidgets.QPushButton(zonesTransformDialog)
        self.folderButton.setMinimumSize(QtCore.QSize(0, 24))
        self.folderButton.setObjectName("folderButton")
        self.gridLayout.addWidget(self.folderButton, 2, 2, 1, 1)
        self.folderLineEdit = QtWidgets.QLineEdit(zonesTransformDialog)
        self.folderLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.folderLineEdit.setObjectName("folderLineEdit")
        self.gridLayout.addWidget(self.folderLineEdit, 2, 1, 1, 1)
        self.mwzInputButton = QtWidgets.QPushButton(zonesTransformDialog)
        self.mwzInputButton.setMinimumSize(QtCore.QSize(0, 24))
        self.mwzInputButton.setObjectName("mwzInputButton")
        self.gridLayout.addWidget(self.mwzInputButton, 1, 2, 1, 1)
        self.mwzInputLineEdit = QtWidgets.QLineEdit(zonesTransformDialog)
        self.mwzInputLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.mwzInputLineEdit.setObjectName("mwzInputLineEdit")
        self.gridLayout.addWidget(self.mwzInputLineEdit, 1, 1, 1, 1)
        self.folderLabel = QtWidgets.QLabel(zonesTransformDialog)
        self.folderLabel.setObjectName("folderLabel")
        self.gridLayout.addWidget(self.folderLabel, 2, 0, 1, 1)
        self.MwZinputLabel = QtWidgets.QLabel(zonesTransformDialog)
        self.MwZinputLabel.setObjectName("MwZinputLabel")
        self.gridLayout.addWidget(self.MwZinputLabel, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.targetLineEdit = QtWidgets.QLineEdit(zonesTransformDialog)
        self.targetLineEdit.setObjectName("targetLineEdit")
        self.gridLayout_2.addWidget(self.targetLineEdit, 3, 1, 1, 1)
        self.targetLabel = QtWidgets.QLabel(zonesTransformDialog)
        self.targetLabel.setObjectName("targetLabel")
        self.gridLayout_2.addWidget(self.targetLabel, 3, 0, 1, 1)
        self.puLabel = QtWidgets.QLabel(zonesTransformDialog)
        self.puLabel.setObjectName("puLabel")
        self.gridLayout_2.addWidget(self.puLabel, 2, 0, 1, 1)
        self.zonesLabel = QtWidgets.QLabel(zonesTransformDialog)
        self.zonesLabel.setObjectName("zonesLabel")
        self.gridLayout_2.addWidget(self.zonesLabel, 4, 0, 1, 1)
        self.puExtLabel = QtWidgets.QLabel(zonesTransformDialog)
        self.puExtLabel.setObjectName("puExtLabel")
        self.gridLayout_2.addWidget(self.puExtLabel, 2, 2, 1, 1)
        self.zonesExtLabel = QtWidgets.QLabel(zonesTransformDialog)
        self.zonesExtLabel.setObjectName("zonesExtLabel")
        self.gridLayout_2.addWidget(self.zonesExtLabel, 4, 2, 1, 1)
        self.puLineEdit = QtWidgets.QLineEdit(zonesTransformDialog)
        self.puLineEdit.setObjectName("puLineEdit")
        self.gridLayout_2.addWidget(self.puLineEdit, 2, 1, 1, 1)
        self.setupLineEdit = QtWidgets.QLineEdit(zonesTransformDialog)
        self.setupLineEdit.setObjectName("setupLineEdit")
        self.gridLayout_2.addWidget(self.setupLineEdit, 1, 1, 1, 1)
        self.setupExtLabel = QtWidgets.QLabel(zonesTransformDialog)
        self.setupExtLabel.setObjectName("setupExtLabel")
        self.gridLayout_2.addWidget(self.setupExtLabel, 1, 2, 1, 1)
        self.setupLabel = QtWidgets.QLabel(zonesTransformDialog)
        self.setupLabel.setObjectName("setupLabel")
        self.gridLayout_2.addWidget(self.setupLabel, 1, 0, 1, 1)
        self.targetExtLabel = QtWidgets.QLabel(zonesTransformDialog)
        self.targetExtLabel.setObjectName("targetExtLabel")
        self.gridLayout_2.addWidget(self.targetExtLabel, 3, 2, 1, 1)
        self.zonesLineEdit = QtWidgets.QLineEdit(zonesTransformDialog)
        self.zonesLineEdit.setObjectName("zonesLineEdit")
        self.gridLayout_2.addWidget(self.zonesLineEdit, 4, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.zoneLabel = QtWidgets.QLabel(zonesTransformDialog)
        self.zoneLabel.setObjectName("zoneLabel")
        self.horizontalLayout_1.addWidget(self.zoneLabel)
        self.zoneComboBox = QtWidgets.QComboBox(zonesTransformDialog)
        self.zoneComboBox.setObjectName("zoneComboBox")
        self.horizontalLayout_1.addWidget(self.zoneComboBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_1.addItem(spacerItem3)
        self.horizontalLayout_1.setStretch(0, 1)
        self.horizontalLayout_1.setStretch(1, 1)
        self.horizontalLayout_1.setStretch(2, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem5)
        self.okButton = QtWidgets.QPushButton(zonesTransformDialog)
        self.okButton.setMinimumSize(QtCore.QSize(0, 24))
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem6)
        self.cancelButton = QtWidgets.QPushButton(zonesTransformDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(0, 24))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem7)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(2, 8)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(zonesTransformDialog)
        self.cancelButton.clicked.connect(zonesTransformDialog.close)
        QtCore.QMetaObject.connectSlotsByName(zonesTransformDialog)

    def retranslateUi(self, zonesTransformDialog):
        _translate = QtCore.QCoreApplication.translate
        zonesTransformDialog.setWindowTitle(_translate("zonesTransformDialog", "Transform CLUZ files from Marxan to Marxan with Zones"))
        self.setupPathLabel.setText(_translate("zonesTransformDialog", "CLUZ setup file for files that will be transformed: "))
        self.folderButton.setText(_translate("zonesTransformDialog", "Browse"))
        self.mwzInputButton.setText(_translate("zonesTransformDialog", "Browse"))
        self.folderLabel.setText(_translate("zonesTransformDialog", "Empty folder for new files"))
        self.MwZinputLabel.setText(_translate("zonesTransformDialog", "Marxan with Zones location"))
        self.targetLabel.setText(_translate("zonesTransformDialog", "New target file name"))
        self.puLabel.setText(_translate("zonesTransformDialog", "New planning unit layer name"))
        self.zonesLabel.setText(_translate("zonesTransformDialog", "New zones file name"))
        self.puExtLabel.setText(_translate("zonesTransformDialog", ".shp"))
        self.zonesExtLabel.setText(_translate("zonesTransformDialog", ".csv"))
        self.setupExtLabel.setText(_translate("zonesTransformDialog", ".clz"))
        self.setupLabel.setText(_translate("zonesTransformDialog", "New Marxan with Zones setup file name"))
        self.targetExtLabel.setText(_translate("zonesTransformDialog", ".csv"))
        self.zoneLabel.setText(_translate("zonesTransformDialog", "Number of zones to be created"))
        self.okButton.setText(_translate("zonesTransformDialog", "OK"))
        self.cancelButton.setText(_translate("zonesTransformDialog", "Cancel"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    zonesTransformDialog = QtWidgets.QDialog()
    ui = Ui_zonesTransformDialog()
    ui.setupUi(zonesTransformDialog)
    zonesTransformDialog.show()
    sys.exit(app.exec_())

