# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rjsmi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz\forms\cluz_form_calibrate.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_calibrateDialog(object):
    def setupUi(self, calibrateDialog):
        calibrateDialog.setObjectName("calibrateDialog")
        calibrateDialog.setMinimumSize(QtCore.QSize(730, 0))
        self.gridLayout = QtWidgets.QGridLayout(calibrateDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(calibrateDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 350))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logos/images/marxan_logo_panel.png"))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.iterLabel = QtWidgets.QLabel(calibrateDialog)
        self.iterLabel.setObjectName("iterLabel")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.iterLabel)
        self.iterLineEdit = QtWidgets.QLineEdit(calibrateDialog)
        self.iterLineEdit.setObjectName("iterLineEdit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.iterLineEdit)
        self.runLabel = QtWidgets.QLabel(calibrateDialog)
        self.runLabel.setObjectName("runLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.runLabel)
        self.runLineEdit = QtWidgets.QLineEdit(calibrateDialog)
        self.runLineEdit.setObjectName("runLineEdit")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.runLineEdit)
        self.spfLineEdit = QtWidgets.QLineEdit(calibrateDialog)
        self.spfLineEdit.setObjectName("spfLineEdit")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.spfLineEdit)
        self.boundLineEdit = QtWidgets.QLineEdit(calibrateDialog)
        self.boundLineEdit.setObjectName("boundLineEdit")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.boundLineEdit)
        self.boundLabel = QtWidgets.QLabel(calibrateDialog)
        self.boundLabel.setObjectName("boundLabel")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.boundLabel)
        self.spfLabel = QtWidgets.QLabel(calibrateDialog)
        self.spfLabel.setObjectName("spfLabel")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.spfLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(11, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.outputLabel = QtWidgets.QLabel(calibrateDialog)
        self.outputLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.outputLabel.setObjectName("outputLabel")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.outputLabel)
        self.outputLineEdit = QtWidgets.QLineEdit(calibrateDialog)
        self.outputLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.outputLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(13, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resultsLineEdit = QtWidgets.QLineEdit(calibrateDialog)
        self.resultsLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.resultsLineEdit.setObjectName("resultsLineEdit")
        self.horizontalLayout_2.addWidget(self.resultsLineEdit)
        self.saveResultsButton = QtWidgets.QPushButton(calibrateDialog)
        self.saveResultsButton.setMinimumSize(QtCore.QSize(0, 20))
        self.saveResultsButton.setObjectName("saveResultsButton")
        self.horizontalLayout_2.addWidget(self.saveResultsButton)
        self.formLayout_2.setLayout(14, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.resultsLabel = QtWidgets.QLabel(calibrateDialog)
        self.resultsLabel.setMinimumSize(QtCore.QSize(20, 0))
        self.resultsLabel.setObjectName("resultsLabel")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.resultsLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem3)
        self.runButton = QtWidgets.QPushButton(calibrateDialog)
        self.runButton.setMinimumSize(QtCore.QSize(0, 20))
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem4)
        self.closeButton = QtWidgets.QPushButton(calibrateDialog)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 20))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem5)
        self.formLayout_2.setLayout(16, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(15, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        self.parameterLabel = QtWidgets.QLabel(calibrateDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterLabel.sizePolicy().hasHeightForWidth())
        self.parameterLabel.setSizePolicy(sizePolicy)
        self.parameterLabel.setMinimumSize(QtCore.QSize(110, 16))
        self.parameterLabel.setObjectName("parameterLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.parameterLabel)
        self.paraComboBox = QtWidgets.QComboBox(calibrateDialog)
        self.paraComboBox.setMinimumSize(QtCore.QSize(0, 20))
        self.paraComboBox.setObjectName("paraComboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.paraComboBox)
        self.numberLabel = QtWidgets.QLabel(calibrateDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberLabel.sizePolicy().hasHeightForWidth())
        self.numberLabel.setSizePolicy(sizePolicy)
        self.numberLabel.setMinimumSize(QtCore.QSize(110, 16))
        self.numberLabel.setObjectName("numberLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.numberLabel)
        self.numberLineEdit = QtWidgets.QLineEdit(calibrateDialog)
        self.numberLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.numberLineEdit.setObjectName("numberLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.numberLineEdit)
        self.maxLineEdit = QtWidgets.QLineEdit(calibrateDialog)
        self.maxLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.maxLineEdit.setObjectName("maxLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.maxLineEdit)
        self.expCheckBox = QtWidgets.QCheckBox(calibrateDialog)
        self.expCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.expCheckBox.setObjectName("expCheckBox")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.expCheckBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        self.minLineEdit = QtWidgets.QLineEdit(calibrateDialog)
        self.minLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.minLineEdit.setObjectName("minLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.minLineEdit)
        self.minLabel = QtWidgets.QLabel(calibrateDialog)
        self.minLabel.setObjectName("minLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.minLabel)
        self.maxLabel = QtWidgets.QLabel(calibrateDialog)
        self.maxLabel.setObjectName("maxLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.maxLabel)
        self.horizontalLayout_3.addLayout(self.formLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(calibrateDialog)
        self.closeButton.clicked.connect(calibrateDialog.close)
        QtCore.QMetaObject.connectSlotsByName(calibrateDialog)

    def retranslateUi(self, calibrateDialog):
        _translate = QtCore.QCoreApplication.translate
        calibrateDialog.setWindowTitle(_translate("calibrateDialog", "Calibrate Marxan parameters"))
        self.iterLabel.setText(_translate("calibrateDialog", "Number of iterations"))
        self.runLabel.setText(_translate("calibrateDialog", "Number of runs"))
        self.boundLabel.setText(_translate("calibrateDialog", "BLM value"))
        self.spfLabel.setText(_translate("calibrateDialog", "SPF value"))
        self.outputLabel.setText(_translate("calibrateDialog", "Marxan output files base name     "))
        self.saveResultsButton.setText(_translate("calibrateDialog", "Save As..."))
        self.resultsLabel.setText(_translate("calibrateDialog", "Results file"))
        self.runButton.setText(_translate("calibrateDialog", "Run Analysis"))
        self.closeButton.setText(_translate("calibrateDialog", "Close"))
        self.parameterLabel.setText(_translate("calibrateDialog", "Parameter to calibrate"))
        self.numberLabel.setText(_translate("calibrateDialog", "Number of analyses"))
        self.expCheckBox.setText(_translate("calibrateDialog", "Use exponential steps between minimum and maximum values"))
        self.minLabel.setText(_translate("calibrateDialog", "Minimum value"))
        self.maxLabel.setText(_translate("calibrateDialog", "Maximum value"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calibrateDialog = QtWidgets.QDialog()
    ui = Ui_calibrateDialog()
    ui.setupUi(calibrateDialog)
    calibrateDialog.show()
    sys.exit(app.exec_())

