# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rjsmi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz\forms\cluz_form_zones_inputs.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_zonesInputsDialog(object):
    def setupUi(self, zonesInputsDialog):
        zonesInputsDialog.setObjectName("zonesInputsDialog")
        zonesInputsDialog.setMinimumSize(QtCore.QSize(620, 430))
        self.gridLayout = QtWidgets.QGridLayout(zonesInputsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(zonesInputsDialog)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logos/images/marxan_logo_panel.png"))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputsLabel = QtWidgets.QLabel(zonesInputsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputsLabel.sizePolicy().hasHeightForWidth())
        self.inputsLabel.setSizePolicy(sizePolicy)
        self.inputsLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.inputsLabel.setTextFormat(QtCore.Qt.PlainText)
        self.inputsLabel.setObjectName("inputsLabel")
        self.verticalLayout_2.addWidget(self.inputsLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.targetBox = QtWidgets.QCheckBox(zonesInputsDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.targetBox.setFont(font)
        self.targetBox.setObjectName("targetBox")
        self.verticalLayout.addWidget(self.targetBox)
        self.puBox = QtWidgets.QCheckBox(zonesInputsDialog)
        self.puBox.setObjectName("puBox")
        self.verticalLayout.addWidget(self.puBox)
        self.zonesBox = QtWidgets.QCheckBox(zonesInputsDialog)
        self.zonesBox.setObjectName("zonesBox")
        self.verticalLayout.addWidget(self.zonesBox)
        self.boundBox = QtWidgets.QCheckBox(zonesInputsDialog)
        self.boundBox.setObjectName("boundBox")
        self.verticalLayout.addWidget(self.boundBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.boundextBox = QtWidgets.QCheckBox(zonesInputsDialog)
        self.boundextBox.setMinimumSize(QtCore.QSize(0, 24))
        self.boundextBox.setObjectName("boundextBox")
        self.horizontalLayout_2.addWidget(self.boundextBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem5)
        self.okButton = QtWidgets.QPushButton(zonesInputsDialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem6)
        self.cancelButton = QtWidgets.QPushButton(zonesInputsDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem7)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 4)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(zonesInputsDialog)
        self.cancelButton.clicked.connect(zonesInputsDialog.close)
        self.boundBox.clicked['bool'].connect(self.boundextBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(zonesInputsDialog)

    def retranslateUi(self, zonesInputsDialog):
        _translate = QtCore.QCoreApplication.translate
        zonesInputsDialog.setWindowTitle(_translate("zonesInputsDialog", "Create Marxan with Zones files"))
        self.inputsLabel.setText(_translate("zonesInputsDialog", "Create the following Marxan with Zones files from the CLUZ files:"))
        self.targetBox.setText(_translate("zonesInputsDialog", "Target and feature files (feat.dat, zonetarget.dat and zonecontrib.dat)"))
        self.puBox.setText(_translate("zonesInputsDialog", "Planning unit files (pu.dat, puzone.dat and pulock.dat)"))
        self.zonesBox.setText(_translate("zonesInputsDialog", "Zones file (zones.dat, costs.dat and zonecost.dat)"))
        self.boundBox.setText(_translate("zonesInputsDialog", "Boundary files (bound.dat and zoneboundcost.dat)"))
        self.boundextBox.setText(_translate("zonesInputsDialog", "Include planning region boundaries"))
        self.okButton.setText(_translate("zonesInputsDialog", "OK"))
        self.cancelButton.setText(_translate("zonesInputsDialog", "Cancel"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    zonesInputsDialog = QtWidgets.QDialog()
    ui = Ui_zonesInputsDialog()
    ui.setupUi(zonesInputsDialog)
    zonesInputsDialog.show()
    sys.exit(app.exec_())

