# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rjsmi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz\forms\cluz_form_zones_change.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ZonesChangeStatusDialog(object):
    def setupUi(self, ZonesChangeStatusDialog):
        ZonesChangeStatusDialog.setObjectName("ZonesChangeStatusDialog")
        ZonesChangeStatusDialog.setMinimumSize(QtCore.QSize(390, 430))
        self.gridLayout = QtWidgets.QGridLayout(ZonesChangeStatusDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logoLabel = QtWidgets.QLabel(ZonesChangeStatusDialog)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/logos/images/marxan_logo.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_2.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.zonesNameLabel = QtWidgets.QLabel(ZonesChangeStatusDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zonesNameLabel.sizePolicy().hasHeightForWidth())
        self.zonesNameLabel.setSizePolicy(sizePolicy)
        self.zonesNameLabel.setMinimumSize(QtCore.QSize(0, 16))
        self.zonesNameLabel.setObjectName("zonesNameLabel")
        self.verticalLayout_2.addWidget(self.zonesNameLabel)
        self.zonesNameComboBox = QtWidgets.QComboBox(ZonesChangeStatusDialog)
        self.zonesNameComboBox.setObjectName("zonesNameComboBox")
        self.verticalLayout_2.addWidget(self.zonesNameComboBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.zonesUnassignedButton = QtWidgets.QRadioButton(ZonesChangeStatusDialog)
        self.zonesUnassignedButton.setChecked(True)
        self.zonesUnassignedButton.setObjectName("zonesUnassignedButton")
        self.verticalLayout.addWidget(self.zonesUnassignedButton)
        self.zonesEarmarkedButton = QtWidgets.QRadioButton(ZonesChangeStatusDialog)
        self.zonesEarmarkedButton.setObjectName("zonesEarmarkedButton")
        self.verticalLayout.addWidget(self.zonesEarmarkedButton)
        self.zonesChangeCheckBox = QtWidgets.QCheckBox(ZonesChangeStatusDialog)
        self.zonesChangeCheckBox.setObjectName("zonesChangeCheckBox")
        self.verticalLayout.addWidget(self.zonesChangeCheckBox)
        self.zonesLockedButton = QtWidgets.QRadioButton(ZonesChangeStatusDialog)
        self.zonesLockedButton.setEnabled(False)
        self.zonesLockedButton.setObjectName("zonesLockedButton")
        self.verticalLayout.addWidget(self.zonesLockedButton)
        self.zonesExcludedButton = QtWidgets.QRadioButton(ZonesChangeStatusDialog)
        self.zonesExcludedButton.setEnabled(False)
        self.zonesExcludedButton.setObjectName("zonesExcludedButton")
        self.verticalLayout.addWidget(self.zonesExcludedButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.zonesMainTargetsMetLabel = QtWidgets.QLabel(ZonesChangeStatusDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zonesMainTargetsMetLabel.sizePolicy().hasHeightForWidth())
        self.zonesMainTargetsMetLabel.setSizePolicy(sizePolicy)
        self.zonesMainTargetsMetLabel.setMinimumSize(QtCore.QSize(0, 16))
        self.zonesMainTargetsMetLabel.setObjectName("zonesMainTargetsMetLabel")
        self.verticalLayout_2.addWidget(self.zonesMainTargetsMetLabel)
        self.zonesZoneTargetsMetLabel = QtWidgets.QLabel(ZonesChangeStatusDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zonesZoneTargetsMetLabel.sizePolicy().hasHeightForWidth())
        self.zonesZoneTargetsMetLabel.setSizePolicy(sizePolicy)
        self.zonesZoneTargetsMetLabel.setMinimumSize(QtCore.QSize(0, 16))
        self.zonesZoneTargetsMetLabel.setObjectName("zonesZoneTargetsMetLabel")
        self.verticalLayout_2.addWidget(self.zonesZoneTargetsMetLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.changeButton = QtWidgets.QPushButton(ZonesChangeStatusDialog)
        self.changeButton.setObjectName("changeButton")
        self.horizontalLayout.addWidget(self.changeButton)
        self.undoButton = QtWidgets.QPushButton(ZonesChangeStatusDialog)
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout.addWidget(self.undoButton)
        self.closeButton = QtWidgets.QPushButton(ZonesChangeStatusDialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 6)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(ZonesChangeStatusDialog)
        self.closeButton.clicked.connect(ZonesChangeStatusDialog.close)
        self.zonesChangeCheckBox.clicked['bool'].connect(self.zonesLockedButton.setEnabled)
        self.zonesChangeCheckBox.clicked['bool'].connect(self.zonesExcludedButton.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ZonesChangeStatusDialog)

    def retranslateUi(self, ZonesChangeStatusDialog):
        _translate = QtCore.QCoreApplication.translate
        ZonesChangeStatusDialog.setWindowTitle(_translate("ZonesChangeStatusDialog", "Change Status panel"))
        self.zonesNameLabel.setText(_translate("ZonesChangeStatusDialog", "Zone name"))
        self.zonesUnassignedButton.setText(_translate("ZonesChangeStatusDialog", "Set as Unassigned"))
        self.zonesEarmarkedButton.setText(_translate("ZonesChangeStatusDialog", "Set as Earmarked"))
        self.zonesChangeCheckBox.setText(_translate("ZonesChangeStatusDialog", "Allow changes\n"
"to Locked and\n"
"Excluded status"))
        self.zonesLockedButton.setText(_translate("ZonesChangeStatusDialog", "Set as Locked In"))
        self.zonesExcludedButton.setText(_translate("ZonesChangeStatusDialog", "Set as Excluded"))
        self.zonesMainTargetsMetLabel.setText(_translate("ZonesChangeStatusDialog", "Targets met: X of Y"))
        self.zonesZoneTargetsMetLabel.setText(_translate("ZonesChangeStatusDialog", "Zone targets met: unspecified"))
        self.changeButton.setText(_translate("ZonesChangeStatusDialog", "Change"))
        self.undoButton.setText(_translate("ZonesChangeStatusDialog", "Undo"))
        self.closeButton.setText(_translate("ZonesChangeStatusDialog", "Close"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ZonesChangeStatusDialog = QtWidgets.QDialog()
    ui = Ui_ZonesChangeStatusDialog()
    ui.setupUi(ZonesChangeStatusDialog)
    ZonesChangeStatusDialog.show()
    sys.exit(app.exec_())

