# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rjsmi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz\forms\cluz_form_zones_load.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_zonesLoadDialog(object):
    def setupUi(self, zonesLoadDialog):
        zonesLoadDialog.setObjectName("zonesLoadDialog")
        zonesLoadDialog.setMinimumSize(QtCore.QSize(700, 430))
        self.gridLayout = QtWidgets.QGridLayout(zonesLoadDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.logoLabel = QtWidgets.QLabel(zonesLoadDialog)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/logos/images/setup_logo_panel.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_6.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.zonesBestCheckBox = QtWidgets.QCheckBox(zonesLoadDialog)
        self.zonesBestCheckBox.setObjectName("zonesBestCheckBox")
        self.verticalLayout.addWidget(self.zonesBestCheckBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.zonesBestLineEdit = QtWidgets.QLineEdit(zonesLoadDialog)
        self.zonesBestLineEdit.setMaxLength(32766)
        self.zonesBestLineEdit.setObjectName("zonesBestLineEdit")
        self.horizontalLayout_2.addWidget(self.zonesBestLineEdit)
        self.zonesBestButton = QtWidgets.QPushButton(zonesLoadDialog)
        self.zonesBestButton.setObjectName("zonesBestButton")
        self.horizontalLayout_2.addWidget(self.zonesBestButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.zonesBestLabel = QtWidgets.QLabel(zonesLoadDialog)
        self.zonesBestLabel.setObjectName("zonesBestLabel")
        self.horizontalLayout_5.addWidget(self.zonesBestLabel)
        self.zonesBestNameLineEdit = QtWidgets.QLineEdit(zonesLoadDialog)
        self.zonesBestNameLineEdit.setObjectName("zonesBestNameLineEdit")
        self.horizontalLayout_5.addWidget(self.zonesBestNameLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.zonesSummedCheckBox = QtWidgets.QCheckBox(zonesLoadDialog)
        self.zonesSummedCheckBox.setObjectName("zonesSummedCheckBox")
        self.verticalLayout.addWidget(self.zonesSummedCheckBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.zonesSummedLineEdit = QtWidgets.QLineEdit(zonesLoadDialog)
        self.zonesSummedLineEdit.setObjectName("zonesSummedLineEdit")
        self.horizontalLayout_3.addWidget(self.zonesSummedLineEdit)
        self.zonesSummedButton = QtWidgets.QPushButton(zonesLoadDialog)
        self.zonesSummedButton.setObjectName("zonesSummedButton")
        self.horizontalLayout_3.addWidget(self.zonesSummedButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.zonesSummedLabel = QtWidgets.QLabel(zonesLoadDialog)
        self.zonesSummedLabel.setObjectName("zonesSummedLabel")
        self.horizontalLayout_4.addWidget(self.zonesSummedLabel)
        self.zonesSummedNameLineEdit = QtWidgets.QLineEdit(zonesLoadDialog)
        self.zonesSummedNameLineEdit.setObjectName("zonesSummedNameLineEdit")
        self.horizontalLayout_4.addWidget(self.zonesSummedNameLineEdit)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem6)
        self.okButton = QtWidgets.QPushButton(zonesLoadDialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem7)
        self.cancelButton = QtWidgets.QPushButton(zonesLoadDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem8)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)

        self.retranslateUi(zonesLoadDialog)
        self.cancelButton.clicked.connect(zonesLoadDialog.close)
        self.zonesBestCheckBox.clicked['bool'].connect(self.zonesBestLabel.setVisible)
        self.zonesBestCheckBox.clicked['bool'].connect(self.zonesBestNameLineEdit.setVisible)
        self.zonesSummedCheckBox.clicked['bool'].connect(self.zonesSummedLabel.setVisible)
        self.zonesSummedCheckBox.clicked['bool'].connect(self.zonesSummedNameLineEdit.setVisible)
        self.zonesBestCheckBox.clicked['bool'].connect(self.zonesBestLineEdit.setVisible)
        self.zonesBestCheckBox.clicked['bool'].connect(self.zonesBestButton.setVisible)
        self.zonesSummedCheckBox.clicked['bool'].connect(self.zonesSummedLineEdit.setVisible)
        self.zonesSummedCheckBox.clicked['bool'].connect(self.zonesSummedButton.setVisible)
        QtCore.QMetaObject.connectSlotsByName(zonesLoadDialog)

    def retranslateUi(self, zonesLoadDialog):
        _translate = QtCore.QCoreApplication.translate
        zonesLoadDialog.setWindowTitle(_translate("zonesLoadDialog", "Load previous Marxan with Zones results"))
        self.zonesBestCheckBox.setText(_translate("zonesLoadDialog", "Load best solution results (default name is *_best.csv)"))
        self.zonesBestButton.setText(_translate("zonesLoadDialog", "Browse"))
        self.zonesBestLabel.setText(_translate("zonesLoadDialog", "New best field name"))
        self.zonesSummedCheckBox.setText(_translate("zonesLoadDialog", "Load summed solution results (default name is *_ssoln.csv)"))
        self.zonesSummedButton.setText(_translate("zonesLoadDialog", "Browse"))
        self.zonesSummedLabel.setText(_translate("zonesLoadDialog", "New summed solution field name prefix"))
        self.okButton.setText(_translate("zonesLoadDialog", "OK"))
        self.cancelButton.setText(_translate("zonesLoadDialog", "Cancel"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    zonesLoadDialog = QtWidgets.QDialog()
    ui = Ui_zonesLoadDialog()
    ui.setupUi(zonesLoadDialog)
    zonesLoadDialog.show()
    sys.exit(app.exec_())

