# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cluz_form_setup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_setupDialog(object):
    def setupUi(self, setupDialog):
        setupDialog.setObjectName(_fromUtf8("setupDialog"))
        setupDialog.resize(832, 457)
        self.gridLayoutWidget = QtGui.QWidget(setupDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 10, 681, 271))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.targLineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.targLineEdit.setObjectName(_fromUtf8("targLineEdit"))
        self.gridLayout.addWidget(self.targLineEdit, 4, 1, 1, 1)
        self.marxanLineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.marxanLineEdit.setObjectName(_fromUtf8("marxanLineEdit"))
        self.gridLayout.addWidget(self.marxanLineEdit, 0, 1, 1, 1)
        self.marxanLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.marxanLabel.setObjectName(_fromUtf8("marxanLabel"))
        self.gridLayout.addWidget(self.marxanLabel, 0, 0, 1, 1)
        self.outputLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.outputLabel.setObjectName(_fromUtf8("outputLabel"))
        self.gridLayout.addWidget(self.outputLabel, 2, 0, 1, 1)
        self.inputLineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.inputLineEdit.setObjectName(_fromUtf8("inputLineEdit"))
        self.gridLayout.addWidget(self.inputLineEdit, 1, 1, 1, 1)
        self.outputButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.outputButton.setMinimumSize(QtCore.QSize(75, 25))
        self.outputButton.setAutoDefault(False)
        self.outputButton.setObjectName(_fromUtf8("outputButton"))
        self.gridLayout.addWidget(self.outputButton, 2, 2, 1, 1)
        self.puLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.puLabel.setMinimumSize(QtCore.QSize(110, 16))
        self.puLabel.setObjectName(_fromUtf8("puLabel"))
        self.gridLayout.addWidget(self.puLabel, 3, 0, 1, 1)
        self.marxanButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.marxanButton.setMinimumSize(QtCore.QSize(75, 25))
        self.marxanButton.setAutoDefault(False)
        self.marxanButton.setObjectName(_fromUtf8("marxanButton"))
        self.gridLayout.addWidget(self.marxanButton, 0, 2, 1, 1)
        self.puLineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.puLineEdit.setObjectName(_fromUtf8("puLineEdit"))
        self.gridLayout.addWidget(self.puLineEdit, 3, 1, 1, 1)
        self.outputLineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.outputLineEdit.setObjectName(_fromUtf8("outputLineEdit"))
        self.gridLayout.addWidget(self.outputLineEdit, 2, 1, 1, 1)
        self.inputLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.inputLabel.setObjectName(_fromUtf8("inputLabel"))
        self.gridLayout.addWidget(self.inputLabel, 1, 0, 1, 1)
        self.targetLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.targetLabel.setObjectName(_fromUtf8("targetLabel"))
        self.gridLayout.addWidget(self.targetLabel, 4, 0, 1, 1)
        self.inputButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.inputButton.setMinimumSize(QtCore.QSize(75, 25))
        self.inputButton.setAutoDefault(False)
        self.inputButton.setObjectName(_fromUtf8("inputButton"))
        self.gridLayout.addWidget(self.inputButton, 1, 2, 1, 1)
        self.puButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.puButton.setMinimumSize(QtCore.QSize(75, 25))
        self.puButton.setAutoDefault(False)
        self.puButton.setObjectName(_fromUtf8("puButton"))
        self.gridLayout.addWidget(self.puButton, 3, 2, 1, 1)
        self.targButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.targButton.setMinimumSize(QtCore.QSize(75, 25))
        self.targButton.setAutoDefault(False)
        self.targButton.setObjectName(_fromUtf8("targButton"))
        self.gridLayout.addWidget(self.targButton, 4, 2, 1, 1)
        self.setupIconLabel = QtGui.QLabel(setupDialog)
        self.setupIconLabel.setGeometry(QtCore.QRect(-10, 20, 141, 381))
        self.setupIconLabel.setText(_fromUtf8(""))
        self.setupIconLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Cluz/icons/icons/setup_logo.png")))
        self.setupIconLabel.setObjectName(_fromUtf8("setupIconLabel"))
        self.horizontalLayoutWidget = QtGui.QWidget(setupDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 400, 471, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.saveButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.saveButton.setMinimumSize(QtCore.QSize(90, 25))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout.addWidget(self.saveButton)
        self.loadButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.loadButton.setMinimumSize(QtCore.QSize(90, 25))
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.horizontalLayout.addWidget(self.loadButton)
        self.saveasButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.saveasButton.setMinimumSize(QtCore.QSize(90, 25))
        self.saveasButton.setObjectName(_fromUtf8("saveasButton"))
        self.horizontalLayout.addWidget(self.saveasButton)
        self.cancelButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setMinimumSize(QtCore.QSize(90, 25))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout.addWidget(self.cancelButton)
        self.setupPathLabel = QtGui.QLabel(setupDialog)
        self.setupPathLabel.setGeometry(QtCore.QRect(160, 330, 651, 31))
        self.setupPathLabel.setObjectName(_fromUtf8("setupPathLabel"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(setupDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(130, 290, 681, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.precLabel = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.precLabel.setMinimumSize(QtCore.QSize(500, 24))
        self.precLabel.setObjectName(_fromUtf8("precLabel"))
        self.horizontalLayout_2.addWidget(self.precLabel)
        self.precComboBox = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.precComboBox.setMinimumSize(QtCore.QSize(0, 24))
        self.precComboBox.setSizeIncrement(QtCore.QSize(0, 16))
        self.precComboBox.setObjectName(_fromUtf8("precComboBox"))
        self.horizontalLayout_2.addWidget(self.precComboBox)

        self.retranslateUi(setupDialog)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), setupDialog.close)
        QtCore.QMetaObject.connectSlotsByName(setupDialog)

    def retranslateUi(self, setupDialog):
        setupDialog.setWindowTitle(_translate("setupDialog", "Setup file settings", None))
        self.targLineEdit.setText(_translate("setupDialog", "blank", None))
        self.marxanLineEdit.setText(_translate("setupDialog", "blank", None))
        self.marxanLabel.setText(_translate("setupDialog", "Marxan location", None))
        self.outputLabel.setText(_translate("setupDialog", "Output directory", None))
        self.inputLineEdit.setText(_translate("setupDialog", "blank", None))
        self.outputButton.setText(_translate("setupDialog", "Browse...", None))
        self.puLabel.setText(_translate("setupDialog", "Planning unit theme", None))
        self.marxanButton.setText(_translate("setupDialog", "Browse...", None))
        self.puLineEdit.setText(_translate("setupDialog", "blank", None))
        self.outputLineEdit.setText(_translate("setupDialog", "blank", None))
        self.inputLabel.setText(_translate("setupDialog", "Input directory", None))
        self.targetLabel.setText(_translate("setupDialog", "Target table", None))
        self.inputButton.setText(_translate("setupDialog", "Browse...", None))
        self.puButton.setText(_translate("setupDialog", "Browse...", None))
        self.targButton.setText(_translate("setupDialog", "Browse...", None))
        self.saveButton.setText(_translate("setupDialog", "Save", None))
        self.loadButton.setText(_translate("setupDialog", "Load", None))
        self.saveasButton.setText(_translate("setupDialog", "Save As...", None))
        self.cancelButton.setText(_translate("setupDialog", "Close", None))
        self.setupPathLabel.setText(_translate("setupDialog", "Setup file location: blank", None))
        self.precLabel.setText(_translate("setupDialog", "Decimal places for numbers in Abundance and Target tables                    ", None))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    setupDialog = QtGui.QDialog()
    ui = Ui_setupDialog()
    ui.setupUi(setupDialog)
    setupDialog.show()
    sys.exit(app.exec_())

