# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rjsmi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz\forms\cluz_form_minpatch.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_minpatchDialog(object):
    def setupUi(self, minpatchDialog):
        minpatchDialog.setObjectName("minpatchDialog")
        minpatchDialog.setMinimumSize(QtCore.QSize(750, 470))
        self.gridLayout_3 = QtWidgets.QGridLayout(minpatchDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.logoLabel = QtWidgets.QLabel(minpatchDialog)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/images/images/setup_logo.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.gridLayout_3.addWidget(self.logoLabel, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(minpatchDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.inputLabel = QtWidgets.QLabel(self.tab1)
        self.inputLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.inputLabel.setObjectName("inputLabel")
        self.verticalLayout_3.addWidget(self.inputLabel)
        self.outputLabel = QtWidgets.QLabel(self.tab1)
        self.outputLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_3.addWidget(self.outputLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minpatchFileLabel = QtWidgets.QLabel(self.tab1)
        self.minpatchFileLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.minpatchFileLabel.setObjectName("minpatchFileLabel")
        self.horizontalLayout_2.addWidget(self.minpatchFileLabel)
        self.detailsLineEdit = QtWidgets.QLineEdit(self.tab1)
        self.detailsLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.detailsLineEdit.setObjectName("detailsLineEdit")
        self.horizontalLayout_2.addWidget(self.detailsLineEdit)
        self.browseButton = QtWidgets.QPushButton(self.tab1)
        self.browseButton.setMinimumSize(QtCore.QSize(0, 24))
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_2.addWidget(self.browseButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.listLabel_2 = QtWidgets.QLabel(self.tab1)
        self.listLabel_2.setMinimumSize(QtCore.QSize(0, 24))
        self.listLabel_2.setObjectName("listLabel_2")
        self.horizontalLayout_3.addWidget(self.listLabel_2)
        self.blmLineEdit = QtWidgets.QLineEdit(self.tab1)
        self.blmLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.blmLineEdit.setObjectName("blmLineEdit")
        self.horizontalLayout_3.addWidget(self.blmLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listLabel = QtWidgets.QLabel(self.tab1)
        self.listLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.listLabel.setObjectName("listLabel")
        self.horizontalLayout_4.addWidget(self.listLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.fileListWidget = QtWidgets.QListWidget(self.tab1)
        self.fileListWidget.setObjectName("fileListWidget")
        self.verticalLayout_3.addWidget(self.fileListWidget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem1)
        self.startButton = QtWidgets.QPushButton(self.tab1)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem2)
        self.closeButton = QtWidgets.QPushButton(self.tab1)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.removeCheckBox = QtWidgets.QCheckBox(self.tab2)
        self.removeCheckBox.setMinimumSize(QtCore.QSize(0, 30))
        self.removeCheckBox.setChecked(True)
        self.removeCheckBox.setObjectName("removeCheckBox")
        self.verticalLayout.addWidget(self.removeCheckBox)
        self.addCheckBox = QtWidgets.QCheckBox(self.tab2)
        self.addCheckBox.setMinimumSize(QtCore.QSize(0, 30))
        self.addCheckBox.setChecked(True)
        self.addCheckBox.setObjectName("addCheckBox")
        self.verticalLayout.addWidget(self.addCheckBox)
        self.whittleCheckBox = QtWidgets.QCheckBox(self.tab2)
        self.whittleCheckBox.setMinimumSize(QtCore.QSize(0, 30))
        self.whittleCheckBox.setChecked(True)
        self.whittleCheckBox.setObjectName("whittleCheckBox")
        self.verticalLayout.addWidget(self.whittleCheckBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.retranslateUi(minpatchDialog)
        self.tabWidget.setCurrentIndex(0)
        self.closeButton.clicked.connect(minpatchDialog.close)
        QtCore.QMetaObject.connectSlotsByName(minpatchDialog)

    def retranslateUi(self, minpatchDialog):
        _translate = QtCore.QCoreApplication.translate
        minpatchDialog.setWindowTitle(_translate("minpatchDialog", "Launch MinPatch"))
        self.inputLabel.setText(_translate("minpatchDialog", "Marxan input folder:"))
        self.outputLabel.setText(_translate("minpatchDialog", "Marxan output folder:"))
        self.minpatchFileLabel.setText(_translate("minpatchDialog", "MinPatch details file"))
        self.browseButton.setText(_translate("minpatchDialog", "Browse"))
        self.listLabel_2.setText(_translate("minpatchDialog", "Boundary Length Modifier Value"))
        self.listLabel.setText(_translate("minpatchDialog", "Marxan files to analyse"))
        self.startButton.setText(_translate("minpatchDialog", "Start MinPatch"))
        self.closeButton.setText(_translate("minpatchDialog", "Close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("minpatchDialog", "Standard options"))
        self.removeCheckBox.setText(_translate("minpatchDialog", "Remove small patches"))
        self.addCheckBox.setText(_translate("minpatchDialog", "Add patches"))
        self.whittleCheckBox.setText(_translate("minpatchDialog", "Simulated whittling"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("minpatchDialog", "Advanced options"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    minpatchDialog = QtWidgets.QDialog()
    ui = Ui_minpatchDialog()
    ui.setupUi(minpatchDialog)
    minpatchDialog.show()
    sys.exit(app.exec_())

