# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cluz_form_calibrate.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_calibrateDialog(object):
    def setupUi(self, calibrateDialog):
        calibrateDialog.setObjectName(_fromUtf8("calibrateDialog"))
        calibrateDialog.resize(730, 482)
        calibrateDialog.setMinimumSize(QtCore.QSize(730, 0))
        self.label = QtGui.QLabel(calibrateDialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 150, 350))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 350))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Cluz/icons/icons/marxan_logo.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayoutWidget = QtGui.QWidget(calibrateDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(320, 430, 201, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.runButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.runButton.setMinimumSize(QtCore.QSize(0, 20))
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.horizontalLayout.addWidget(self.runButton)
        self.closeButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 20))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout.addWidget(self.closeButton)
        self.formLayoutWidget = QtGui.QWidget(calibrateDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(190, 30, 511, 111))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.parameterLabel = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterLabel.sizePolicy().hasHeightForWidth())
        self.parameterLabel.setSizePolicy(sizePolicy)
        self.parameterLabel.setMinimumSize(QtCore.QSize(110, 16))
        self.parameterLabel.setObjectName(_fromUtf8("parameterLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.parameterLabel)
        self.paraComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.paraComboBox.setMinimumSize(QtCore.QSize(0, 20))
        self.paraComboBox.setObjectName(_fromUtf8("paraComboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.paraComboBox)
        self.numberLabel = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberLabel.sizePolicy().hasHeightForWidth())
        self.numberLabel.setSizePolicy(sizePolicy)
        self.numberLabel.setMinimumSize(QtCore.QSize(110, 16))
        self.numberLabel.setObjectName(_fromUtf8("numberLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.numberLabel)
        self.numberLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.numberLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.numberLineEdit.setObjectName(_fromUtf8("numberLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.numberLineEdit)
        self.minLabel = QtGui.QLabel(self.formLayoutWidget)
        self.minLabel.setObjectName(_fromUtf8("minLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.minLabel)
        self.minLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.minLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.minLineEdit.setObjectName(_fromUtf8("minLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.minLineEdit)
        self.maxLabel = QtGui.QLabel(self.formLayoutWidget)
        self.maxLabel.setObjectName(_fromUtf8("maxLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.maxLabel)
        self.maxLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.maxLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.maxLineEdit.setObjectName(_fromUtf8("maxLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.maxLineEdit)
        self.expCheckBox = QtGui.QCheckBox(calibrateDialog)
        self.expCheckBox.setGeometry(QtCore.QRect(190, 150, 531, 20))
        self.expCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.expCheckBox.setObjectName(_fromUtf8("expCheckBox"))
        self.formLayoutWidget_2 = QtGui.QWidget(calibrateDialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(190, 190, 511, 91))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.iterLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.iterLabel.setObjectName(_fromUtf8("iterLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.iterLabel)
        self.iterLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.iterLineEdit.setObjectName(_fromUtf8("iterLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.iterLineEdit)
        self.runLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.runLabel.setObjectName(_fromUtf8("runLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.runLabel)
        self.runLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.runLineEdit.setObjectName(_fromUtf8("runLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.runLineEdit)
        self.boundLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.boundLabel.setObjectName(_fromUtf8("boundLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.boundLabel)
        self.boundLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.boundLineEdit.setObjectName(_fromUtf8("boundLineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.boundLineEdit)
        self.formLayoutWidget_3 = QtGui.QWidget(calibrateDialog)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(190, 310, 511, 41))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.outputLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.outputLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.outputLabel.setObjectName(_fromUtf8("outputLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.outputLabel)
        self.outputLineEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.outputLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.outputLineEdit.setObjectName(_fromUtf8("outputLineEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.outputLineEdit)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(calibrateDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(190, 360, 511, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.resultsLabel = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.resultsLabel.setMinimumSize(QtCore.QSize(20, 0))
        self.resultsLabel.setObjectName(_fromUtf8("resultsLabel"))
        self.horizontalLayout_2.addWidget(self.resultsLabel)
        self.resultsLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.resultsLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.resultsLineEdit.setObjectName(_fromUtf8("resultsLineEdit"))
        self.horizontalLayout_2.addWidget(self.resultsLineEdit)
        self.saveResultsButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.saveResultsButton.setMinimumSize(QtCore.QSize(0, 20))
        self.saveResultsButton.setObjectName(_fromUtf8("saveResultsButton"))
        self.horizontalLayout_2.addWidget(self.saveResultsButton)

        self.retranslateUi(calibrateDialog)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL(_fromUtf8("clicked()")), calibrateDialog.close)
        QtCore.QMetaObject.connectSlotsByName(calibrateDialog)

    def retranslateUi(self, calibrateDialog):
        calibrateDialog.setWindowTitle(_translate("calibrateDialog", "Calibrate Marxan parameters", None))
        self.runButton.setText(_translate("calibrateDialog", "Run Analysis", None))
        self.closeButton.setText(_translate("calibrateDialog", "Close", None))
        self.parameterLabel.setText(_translate("calibrateDialog", "Parameter to calibrate", None))
        self.numberLabel.setText(_translate("calibrateDialog", "Number of analyses", None))
        self.minLabel.setText(_translate("calibrateDialog", "Minimum value", None))
        self.maxLabel.setText(_translate("calibrateDialog", "Maximum value", None))
        self.expCheckBox.setText(_translate("calibrateDialog", "Use exponential steps between minimum and maximum values", None))
        self.iterLabel.setText(_translate("calibrateDialog", "Number of iterations", None))
        self.runLabel.setText(_translate("calibrateDialog", "Number of runs", None))
        self.boundLabel.setText(_translate("calibrateDialog", "BLM value", None))
        self.outputLabel.setText(_translate("calibrateDialog", "Marxan output files base name     ", None))
        self.resultsLabel.setText(_translate("calibrateDialog", "Results file", None))
        self.saveResultsButton.setText(_translate("calibrateDialog", "Save As...", None))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    calibrateDialog = QtGui.QDialog()
    ui = Ui_calibrateDialog()
    ui.setupUi(calibrateDialog)
    calibrateDialog.show()
    sys.exit(app.exec_())

