# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cluz_form_marxan.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_marxanDialog(object):
    def setupUi(self, marxanDialog):
        marxanDialog.setObjectName(_fromUtf8("marxanDialog"))
        marxanDialog.resize(715, 500)
        marxanDialog.setMinimumSize(QtCore.QSize(710, 500))
        self.label = QtGui.QLabel(marxanDialog)
        self.label.setGeometry(QtCore.QRect(10, 40, 151, 351))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Cluz/icons/icons/marxan_logo.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayoutWidget = QtGui.QWidget(marxanDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(290, 440, 261, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.startButton.setMinimumSize(QtCore.QSize(0, 16))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout.addWidget(self.startButton)
        self.closeButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 16))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout.addWidget(self.closeButton)
        self.tabWidget = QtGui.QTabWidget(marxanDialog)
        self.tabWidget.setGeometry(QtCore.QRect(190, 20, 461, 371))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.formLayoutWidget = QtGui.QWidget(self.tab1)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 431, 151))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.iterLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.iterLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.iterLineEdit.setObjectName(_fromUtf8("iterLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.iterLineEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem)
        self.runLabel = QtGui.QLabel(self.formLayoutWidget)
        self.runLabel.setMinimumSize(QtCore.QSize(150, 24))
        self.runLabel.setObjectName(_fromUtf8("runLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.runLabel)
        self.runLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.runLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.runLineEdit.setObjectName(_fromUtf8("runLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.runLineEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(5, QtGui.QFormLayout.LabelRole, spacerItem1)
        self.outputLabel = QtGui.QLabel(self.formLayoutWidget)
        self.outputLabel.setMinimumSize(QtCore.QSize(150, 24))
        self.outputLabel.setObjectName(_fromUtf8("outputLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.outputLabel)
        self.outputLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.outputLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.outputLineEdit.setObjectName(_fromUtf8("outputLineEdit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.outputLineEdit)
        self.iterLabel = QtGui.QLabel(self.formLayoutWidget)
        self.iterLabel.setMinimumSize(QtCore.QSize(150, 24))
        self.iterLabel.setObjectName(_fromUtf8("iterLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.iterLabel)
        self.gridLayoutWidget = QtGui.QWidget(self.tab1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 170, 431, 80))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.boundCheckBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.boundCheckBox.setMinimumSize(QtCore.QSize(180, 24))
        self.boundCheckBox.setObjectName(_fromUtf8("boundCheckBox"))
        self.gridLayout.addWidget(self.boundCheckBox, 0, 0, 1, 1)
        self.boundLineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.boundLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.boundLineEdit.setText(_fromUtf8(""))
        self.boundLineEdit.setObjectName(_fromUtf8("boundLineEdit"))
        self.gridLayout.addWidget(self.boundLineEdit, 0, 1, 1, 1)
        self.extraCheckBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.extraCheckBox.setMinimumSize(QtCore.QSize(280, 24))
        self.extraCheckBox.setObjectName(_fromUtf8("extraCheckBox"))
        self.gridLayout.addWidget(self.extraCheckBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.extraTab = QtGui.QWidget()
        self.extraTab.setObjectName(_fromUtf8("extraTab"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.extraTab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 431, 161))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.propLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.propLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.propLineEdit.setObjectName(_fromUtf8("propLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.propLineEdit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout_2.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem2)
        self.missingLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.missingLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.missingLineEdit.setObjectName(_fromUtf8("missingLineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.missingLineEdit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout_2.setItem(3, QtGui.QFormLayout.LabelRole, spacerItem3)
        self.parallelCheckBox = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.parallelCheckBox.setMinimumSize(QtCore.QSize(0, 24))
        self.parallelCheckBox.setObjectName(_fromUtf8("parallelCheckBox"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.parallelCheckBox)
        self.propLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.propLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.propLabel.setObjectName(_fromUtf8("propLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.propLabel)
        self.missingLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.missingLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.missingLabel.setWordWrap(True)
        self.missingLabel.setObjectName(_fromUtf8("missingLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.missingLabel)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.extraTab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 190, 331, 105))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.parallelListWidget = QtGui.QListWidget(self.gridLayoutWidget_2)
        self.parallelListWidget.setEnabled(False)
        self.parallelListWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.parallelListWidget.setObjectName(_fromUtf8("parallelListWidget"))
        self.gridLayout_2.addWidget(self.parallelListWidget, 1, 3, 1, 1)
        self.parallelLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.parallelLabel.setEnabled(False)
        self.parallelLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.parallelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.parallelLabel.setObjectName(_fromUtf8("parallelLabel"))
        self.gridLayout_2.addWidget(self.parallelLabel, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 1)
        self.tabWidget.addTab(self.extraTab, _fromUtf8(""))

        self.retranslateUi(marxanDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL(_fromUtf8("clicked()")), marxanDialog.close)
        QtCore.QObject.connect(self.boundCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.boundLineEdit.setVisible)
        QtCore.QObject.connect(self.parallelCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.parallelLabel.setEnabled)
        QtCore.QObject.connect(self.parallelCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.parallelListWidget.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(marxanDialog)

    def retranslateUi(self, marxanDialog):
        marxanDialog.setWindowTitle(_translate("marxanDialog", "Launch Marxan", None))
        self.startButton.setText(_translate("marxanDialog", "Start Marxan", None))
        self.closeButton.setText(_translate("marxanDialog", "Close", None))
        self.runLabel.setText(_translate("marxanDialog", "Number of runs", None))
        self.outputLabel.setText(_translate("marxanDialog", "Output file name", None))
        self.iterLabel.setText(_translate("marxanDialog", "Number of iterations", None))
        self.boundCheckBox.setText(_translate("marxanDialog", "Include boundary cost (BLM)", None))
        self.extraCheckBox.setText(_translate("marxanDialog", "Produce extra Marxan outputs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("marxanDialog", "Standard options", None))
        self.parallelCheckBox.setText(_translate("marxanDialog", "Run parallel Marxan analyses", None))
        self.propLabel.setText(_translate("marxanDialog", "Starting proportion", None))
        self.missingLabel.setText(_translate("marxanDialog", "Species missing if target proportion is lower than", None))
        self.parallelLabel.setText(_translate("marxanDialog", "Number of parallel analyses", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.extraTab), _translate("marxanDialog", "Advanced options", None))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    marxanDialog = QtGui.QDialog()
    ui = Ui_marxanDialog()
    ui.setupUi(marxanDialog)
    marxanDialog.show()
    sys.exit(app.exec_())

