# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rjsmi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz\forms\cluz_form_convert_csv.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_convertCsvDialog(object):
    def setupUi(self, convertCsvDialog):
        convertCsvDialog.setObjectName("convertCsvDialog")
        convertCsvDialog.setMinimumSize(QtCore.QSize(730, 380))
        self.gridLayout = QtWidgets.QGridLayout(convertCsvDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.setupIconLabel = QtWidgets.QLabel(convertCsvDialog)
        self.setupIconLabel.setText("")
        self.setupIconLabel.setPixmap(QtGui.QPixmap(":/logos/images/setup_logo_panel.png"))
        self.setupIconLabel.setObjectName("setupIconLabel")
        self.horizontalLayout_5.addWidget(self.setupIconLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.csvLabel = QtWidgets.QLabel(convertCsvDialog)
        self.csvLabel.setObjectName("csvLabel")
        self.verticalLayout_2.addWidget(self.csvLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.csvFileLineEdit = QtWidgets.QLineEdit(convertCsvDialog)
        self.csvFileLineEdit.setObjectName("csvFileLineEdit")
        self.horizontalLayout_4.addWidget(self.csvFileLineEdit)
        self.browseButton = QtWidgets.QPushButton(convertCsvDialog)
        self.browseButton.setMinimumSize(QtCore.QSize(0, 22))
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_4.addWidget(self.browseButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.idfieldLabel = QtWidgets.QLabel(convertCsvDialog)
        self.idfieldLabel.setMinimumSize(QtCore.QSize(151, 16))
        self.idfieldLabel.setObjectName("idfieldLabel")
        self.horizontalLayout_3.addWidget(self.idfieldLabel)
        self.idfieldComboBox = QtWidgets.QComboBox(convertCsvDialog)
        self.idfieldComboBox.setObjectName("idfieldComboBox")
        self.horizontalLayout_3.addWidget(self.idfieldComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.noneRadioButton = QtWidgets.QRadioButton(convertCsvDialog)
        self.noneRadioButton.setMinimumSize(QtCore.QSize(441, 20))
        self.noneRadioButton.setObjectName("noneRadioButton")
        self.verticalLayout_2.addWidget(self.noneRadioButton)
        self.userRadioButton = QtWidgets.QRadioButton(convertCsvDialog)
        self.userRadioButton.setMinimumSize(QtCore.QSize(0, 20))
        self.userRadioButton.setObjectName("userRadioButton")
        self.verticalLayout_2.addWidget(self.userRadioButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.convLabel = QtWidgets.QLabel(convertCsvDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convLabel.sizePolicy().hasHeightForWidth())
        self.convLabel.setSizePolicy(sizePolicy)
        self.convLabel.setMinimumSize(QtCore.QSize(151, 20))
        self.convLabel.setObjectName("convLabel")
        self.horizontalLayout_2.addWidget(self.convLabel)
        self.convLineEdit = QtWidgets.QLineEdit(convertCsvDialog)
        self.convLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.convLineEdit.setObjectName("convLineEdit")
        self.horizontalLayout_2.addWidget(self.convLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem4)
        self.okButton = QtWidgets.QPushButton(convertCsvDialog)
        self.okButton.setMinimumSize(QtCore.QSize(0, 22))
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem5)
        self.cancelButton = QtWidgets.QPushButton(convertCsvDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(0, 22))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem6)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 2)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 1)
        self.verticalLayout_2.setStretch(7, 1)
        self.verticalLayout_2.setStretch(8, 1)
        self.verticalLayout_2.setStretch(9, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(convertCsvDialog)
        self.cancelButton.clicked.connect(convertCsvDialog.close)
        self.userRadioButton.toggled['bool'].connect(self.convLabel.setEnabled)
        self.userRadioButton.toggled['bool'].connect(self.convLineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(convertCsvDialog)

    def retranslateUi(self, convertCsvDialog):
        _translate = QtCore.QCoreApplication.translate
        convertCsvDialog.setWindowTitle(_translate("convertCsvDialog", "Convert themes to abundance data"))
        self.csvLabel.setText(_translate("convertCsvDialog", "Select csv file to import data into Marxan"))
        self.browseButton.setText(_translate("convertCsvDialog", "Browse"))
        self.idfieldLabel.setText(_translate("convertCsvDialog", "Layer planning unit ID field name"))
        self.noneRadioButton.setText(_translate("convertCsvDialog", "No conversion (results will be in layer measurement units)"))
        self.userRadioButton.setText(_translate("convertCsvDialog", "User defined conversion"))
        self.convLabel.setText(_translate("convertCsvDialog", "         Area conversion value"))
        self.okButton.setText(_translate("convertCsvDialog", "OK"))
        self.cancelButton.setText(_translate("convertCsvDialog", "Cancel"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    convertCsvDialog = QtWidgets.QDialog()
    ui = Ui_convertCsvDialog()
    ui.setupUi(convertCsvDialog)
    convertCsvDialog.show()
    sys.exit(app.exec_())

